name: Update Postman Collection

on:
  push:
    branches:
      - master

jobs:
  build-and-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Build the application
        run: dotnet build -c Debug

      - name: Install Swashbuckle CLI
        run: dotnet tool install --global swashbuckle.aspnetcore.cli

      - name: Update PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate swagger
        run: |
          DLL_FILE="$(find bin/Debug/net8.0 -name '*.dll' 2>/dev/null | head -n 1)"
          if [ -z "$DLL_FILE" ]; then
            echo "❌ Could not find a DLL in bin/Debug/net8.0"
            exit 1
          fi
          dotnet swagger tofile --output swagger.json "$DLL_FILE" v1

      - name: Upload swagger as artifact
        uses: actions/upload-artifact@v2
        with:
          name: swagger
          path: swagger.json

      - name: Push swagger to Postman
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}
        run: |
          curl -X PUT "https://api.getpostman.com/collections/${POSTMAN_COLLECTION_ID}" \
              -H "X-API-Key: ${POSTMAN_API_KEY}" \
              -H "Content-Type: application/json" \
              -d @swagger.json
