name: Update Postman Collection

on:
  push:
    branches:
      - master

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Build the application
        run: dotnet build -c Debug

      - name: Install Swashbuckle CLI
        run: dotnet tool install --global swashbuckle.aspnetcore.cli

      - name: Add .dotnet/tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate swagger
        run: |
          DLL_FILE="$(find bin/Debug/net8.0 -name '*.dll' | head -n 1)"
          dotnet swagger tofile --output swagger.json "$DLL_FILE" v1

      - name: Update Postman collection
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}
        run: |
          curl -X PUT "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_ID" \
               -H "X-API-Key: $POSTMAN_API_KEY" \
               -d @swagger.json
