- name: Publish application
  run: dotnet publish -c Release

- name: Start application
  run: |
    dotnet Your.Api.dll & 
    APP_ID=$! 
    sleep 10
    curl -s http://localhost:5000/swagger/v1/swagger.json -o swagger.json
    kill $APP_ID

- name: Push swagger to Postman
  env:
    POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
    POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}
  run: |
    curl -X PUT "https://api.getpostman.com/collections/${POSTMAN_COLLECTION_ID}" \
         -H "X-API-Key: ${POSTMAN_API_KEY}" \
         -H "Content-Type: application/json" \
         -d @swagger.json
